# Generated by Django 5.1.3 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
