# Generated by Django 5.1.3 on 2024-12-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_regionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.regionuser'),
        ),
        migrations.AlterField(
            model_name='regionuser',
            name='city',
            field=models.CharField(choices=[('almaty', 'Almaty'), ('astana', 'Astana'), ('shymkent', 'Shymkent'), ('aktobe', 'Aktobe'), ('karaganda', 'Karaganda')], max_length=100, null=True),
        ),
    ]
