# Generated by Django 5.1.3 on 2024-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_img/'),
        ),
    ]
