# Generated by Django 5.1.3 on 2024-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_genres_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('history', 'History'), ('self-help', 'Self-Help')], default='Fiction', max_length=100),
        ),
        migrations.AlterField(
            model_name='regionuser',
            name='city',
            field=models.CharField(blank=True, choices=[('almaty', 'Almaty'), ('astana', 'Astana'), ('shymkent', 'Shymkent'), ('aktobe', 'Aktobe'), ('karaganda', 'Karaganda')], default='Almaty', max_length=100),
        ),
    ]
