# Generated by Django 5.1.3 on 2024-12-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.book'),
        ),
    ]
