# Generated by Django 5.1.3 on 2024-12-29 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='book_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_img/avtr.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
