# Generated by Django 5.1.5 on 2025-01-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customuser_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
