# Generated by Django 5.1.5 on 2025-02-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.regionuser'),
        ),
    ]
